<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="PC155" failures="1" tests="1" name="api_functional_integration.TestCase_F004_Agent" time="2716.704" errors="0" timestamp="2021-09-07T01:59:39 PKT" skipped="0">
  <testcase classname="api_functional_integration.TestCase_F004_Agent" name="testCase_F004_Agent" time="2716.704">
    <failure message="Failed to verify: Did any of these people lose qualifying health coverage between Jul 8, 2021 and Sep 6, 2021? expected [Did any of these people lose qualifying health coverage between Jul 9, 2021 and Sep 7, 2021?] but found [Did any of these people lose qualifying health coverage between Jul 8, 2021 and Sep 6, 2021?]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Failed to verify: Did any of these people lose qualifying health coverage between Jul 8, 2021 and Sep 6, 2021? expected [Did any of these people lose qualifying health coverage between Jul 9, 2021 and Sep 7, 2021?] but found [Did any of these people lose qualifying health coverage between Jul 8, 2021 and Sep 6, 2021?]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at pages.CommonMethodPage.verifyS083(CommonMethodPage.java:1380)
at api_functional_integration.TestCase_F004_Agent.testCase_F004_Agent(TestCase_F004_Agent.java:1408)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- testCase_F004_Agent -->
  <system-out/>
</testsuite> <!-- api_functional_integration.TestCase_F004_Agent -->
